### ISSUE TITLE
Can this package calculate biogeographical graves besides cradle and museum?

### ISSUE THREAD

**Issue by Otoliths** [ropensci/canaper#14]
Hi, @joelnitta 

This package is fantastic! 
As Rangel et al.(2018) define them here, “cradles” are about speciation, “museums” about persistence, and “graves” about extinctions. In other words, locations with unusually high rates of speciation as “cradles” of diversity, and to locations with unusually low rates of extinction as “museums.”, and “graves”—locations with unusually high extinction rates. In addition to biogeographical cradle (Neo-endemism) and museum (Paleo-endemism), can this package calculate biogeographical graves?

- Rangel TF, Edwards NR, Holden PB, Diniz-Filho JA, Gosling WD, Coelho MT, Cassemiro FA, Rahbek C, Colwell RK. Modeling the ecology and evolution of biodiversity: Biogeographical cradles, museums, and graves. _Science_. 2018 Jul 20;361(6399):eaar5452.

**Comment by joelnitta** [comment]
Thanks for the comment @Otoliths!

I think the definition of cradles, museums, and graves may be a bit different from what canaper measures, which is phylogenetic endemism. For cradles, museums, and graves, I think you want to look at **speciation rate**, not degree of phylogenetic endemism. canaper does not measure speciation rate. One popular (but somewhat controversial) package to do that is [BAMMtools](https://cran.r-project.org/web/packages/BAMMtools/index.html); the MiSSE method available in [hisse](https://cran.r-project.org/web/packages/hisse/index.html) is another more recently developed alternative (Ref 1). Once you have an estimation of speciation rates, you would need to somehow characterize regional speciation rates, then determine if any are significantly high or low. I think various studies have done this (e.g. Ref 2), but I am not aware of a standard method.

So I think this is an interesting idea, but the estimation of speciation rates in the first place is not straightforward, and is beyond the scope of canaper. As such I am closing this issue, but feel free to continue the discussion in this issue if you have any more comments. 

Ref 1: Vasconcelos, T., O’Meara, B.C. and Beaulieu, J.M. (2022) ‘A flexible method for estimating tip diversification rates across a range of speciation and extinction scenarios’, Evolution, p. evo.14517. Available at: https://doi.org/10.1111/evo.14517.

Ref 2: Igea, J. and Tanentzap, A.J. (2019) ‘Multiple macroevolutionary routes to becoming a biodiversity hotspot’, Science Advances, 5(2), p. eaau8067. Available at: https://doi.org/10/ghppj2.
